//$file${../../include/qm~::CameraGrabber.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${../../include/qm~::CameraGrabber.hpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../../include/qm~::CameraGrabber.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef CAMERA_GRABBER_HPP_
#define CAMERA_GRABBER_HPP_

#include "qpcpp.hpp"
#include "ICameraGrabber.hpp"
#include "LoggerInterface.hpp"
#include "GofkuCamCommon.hpp"
#include "DepthEstimatorController.hpp"

namespace GofkuCam
{

//$declare${Components::CameraGrabber} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::CameraGrabber} ...............................................
class CameraGrabber : public QP::QActive {
private:
    LoggerInterfacePtr m_logger;

public:
    std::shared_ptr<ICameraGrabber> m_icamera_grabber;

public:
    CameraGrabber(
        LoggerInterfacePtr logger,
        std::string source,
        std::vector<std::shared_ptr<DepthEstimatorController>>  depth_estimator_controllers);

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(NOT_STARTED);
    Q_STATE_DECL(RUNNING);
}; // class CameraGrabber
//$enddecl${Components::CameraGrabber} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam

#endif
