//$file${../../include/qm~::DepthEstimatorController.hpp} vvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${../../include/qm~::DepthEstimatorController.hpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../../include/qm~::DepthEstimatorController.hpp} ^^^^^^^^^^^^^^^^^
#ifndef DEPTH_ESTIMATOR_CONTROLLER_HPP_
#define DEPTH_ESTIMATOR_CONTROLLER_HPP_

#include "qpcpp.hpp"
#include "LoggerInterface.hpp"
#include "DepthEstimator.hpp"
#include "IDetectorController.hpp"

namespace GofkuCam
{

//$declare${Components::DepthEstimatorController} vvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::DepthEstimatorController} ....................................
class DepthEstimatorController : public QP::QActive {
private:
    LoggerInterfacePtr m_logger;

public:
    std::shared_ptr<IDetectorController> m_depth_estimator_controller;

public:
    DepthEstimatorController(LoggerInterfacePtr logger);

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(operating);
    Q_STATE_DECL(NOT_STARTED);
}; // class DepthEstimatorController
//$enddecl${Components::DepthEstimatorController} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam

#endif
