//$file${../../include/qm~::Evts.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${../../include/qm~::Evts.hpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../../include/qm~::Evts.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef EVTS_HPP_
#define EVTS_HPP_

#include "qpcpp.hpp"
#include <variant>
#include "Signals.hpp"

//$declare${Evts} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace GofkuCam {

//${Evts::EvtSignals} ........................................................
enum EvtSignals : QP::QSignal {
    IMMEDIATE_TRANSITION_SIG = QP::Q_USER_SIG,

    TIMER_TIMEDOUT_SIG,
    FRAME_CAPTURED_SIG,
    FRAME_GRABBING_FAILED_SIG,

    MAX_GOFKU_CAM_SIG
};

//${Evts::FrameCapturedEvt} ..................................................
class FrameCapturedEvt : public QP::QEvt {
public:
    FrameCapturedEvt()
    : QEvt(EvtSignals::FRAME_CAPTURED_SIG)
    {}
}; // class FrameCapturedEvt

//${Evts::TimerTimedOut} .....................................................
class TimerTimedOut : public QP::QEvt {
public:
    TimerTimedOut()
    : QEvt(EvtSignals::TIMER_TIMEDOUT_SIG)
    {}
}; // class TimerTimedOut

//${Evts::FrameGrabbingFailed} ...............................................
class FrameGrabbingFailed : public QP::QEvt {
public:
    FrameGrabbingFailed();
}; // class FrameGrabbingFailed

} // namespace GofkuCam
//$enddecl${Evts} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

namespace GofkuCam
{
    using EventTyp     = std::variant<FrameCapturedEvt, TimerTimedOut, FrameGrabbingFailed>;
} // namespace GofkuCam

#endif
