//$file${../../include/qm~::Evts.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${../../include/qm~::Evts.hpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../../include/qm~::Evts.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef EVTS_HPP_
#define EVTS_HPP_

#include "qpcpp.hpp"
#include "GofkuCamCommon.hpp"
#include <memory>

//$declare${Evts} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace GofkuCam {

//${Evts::EvtSignals} ........................................................
enum EvtSignals : QP::QSignal
{
    FRAME_TIMER_TIMEOUT_SIG  = QP::Q_USER_SIG,
    POLLING_TIMER_TIMEOUT_SIG,
    FRAME_CAPTURED_SIG,
    STREAM_ENDED_SIG,
    CAPTURE_ERROR_SIG,
    START_REQ_SIG,
    STOP_REQ_SIG,
    OBJECT_DETECTION_COMPLETED_SIG,
    DEPTH_ESTIMATION_COMPLETED_SIG,
    CAT_FEEDING_DETERMINED_SIG,
    RECONNECTION_TIMER_TIMED_OUT_SIG,
    CONNECTED_TO_BROKER_SIG,
    DISCONNECTED_FROM_BROKER_SIG,

    MAX_GOFKU_CAM_SIG
};

//${Evts::FrameCapturedEvt} ..................................................
class FrameCapturedEvt : public QP::QEvt {
public:
    std::shared_ptr<Frame> m_frame;

public:
    FrameCapturedEvt()
    : QEvt(EvtSignals::FRAME_CAPTURED_SIG)
    , m_frame{nullptr}
    {}
}; // class FrameCapturedEvt

//${Evts::FrameTimerTimeout} .................................................
class FrameTimerTimeout : public QP::QEvt {
public:
    FrameTimerTimeout()
    : QEvt(EvtSignals::FRAME_TIMER_TIMEOUT_SIG)
    {}
}; // class FrameTimerTimeout

//${Evts::StreamEnded} .......................................................
class StreamEnded : public QP::QEvt {
public:
    StreamEnded();
}; // class StreamEnded

//${Evts::CaptureError} ......................................................
class CaptureError : public QP::QEvt {
public:
    CaptureError();
}; // class CaptureError

//${Evts::StopRequested} .....................................................
class StopRequested : public QP::QEvt {
public:
    StopRequested();
}; // class StopRequested

//${Evts::StartRequested} ....................................................
class StartRequested : public QP::QEvt {
public:
    StartRequested();
}; // class StartRequested

//${Evts::PollingTimerTimeout} ...............................................
class PollingTimerTimeout : public QP::QEvt {
public:
    PollingTimerTimeout();
}; // class PollingTimerTimeout

//${Evts::ObjectDetectionCompletedEvt} .......................................
class ObjectDetectionCompletedEvt : public QP::QEvt {
public:
    std::shared_ptr<std::vector<Detection>> m_cat_or_dog_detections;

public:
    ObjectDetectionCompletedEvt()
    : QEvt(EvtSignals::OBJECT_DETECTION_COMPLETED_SIG)
    , m_cat_or_dog_detections{nullptr}
    {}
}; // class ObjectDetectionCompletedEvt

//${Evts::DepthEstimationCompletedEvt} .......................................
class DepthEstimationCompletedEvt : public QP::QEvt {
public:
    std::shared_ptr<Frame> m_depth_frame;

public:
    DepthEstimationCompletedEvt()
    : QEvt(EvtSignals::DEPTH_ESTIMATION_COMPLETED_SIG)
    , m_depth_frame{nullptr}
    {}
}; // class DepthEstimationCompletedEvt

//${Evts::CatFeedingDetermined} ..............................................
class CatFeedingDetermined : public QP::QEvt {
public:
    std::shared_ptr<HakuStatus> m_haku_status;

public:
    CatFeedingDetermined()
    : QEvt(EvtSignals::CAT_FEEDING_DETERMINED_SIG)
    , m_haku_status{nullptr}
    {}
}; // class CatFeedingDetermined

//${Evts::ReconnectionTimerTimerTimeout} .....................................
class ReconnectionTimerTimerTimeout : public QP::QEvt {
public:
    ReconnectionTimerTimerTimeout()
    : QEvt(EvtSignals::RECONNECTION_TIMER_TIMED_OUT_SIG)
    {}
}; // class ReconnectionTimerTimerTimeout

//${Evts::DisconnectedFromBroker} ............................................
class DisconnectedFromBroker : public QP::QEvt {
public:
    DisconnectedFromBroker()
    : QEvt(EvtSignals::DISCONNECTED_FROM_BROKER_SIG)
    {}
}; // class DisconnectedFromBroker

//${Evts::ConnectedToBroker} .................................................
class ConnectedToBroker : public QP::QEvt {
public:
    ConnectedToBroker()
    : QEvt(EvtSignals::CONNECTED_TO_BROKER_SIG)
    {}
}; // class ConnectedToBroker

} // namespace GofkuCam
//$enddecl${Evts} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
