//$file${../../include/qm~::Evts.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${../../include/qm~::Evts.hpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../../include/qm~::Evts.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef EVTS_HPP_
#define EVTS_HPP_

#include "qpcpp.hpp"
#include "GofkuCamCommon.hpp"
#include <memory>

//$declare${Evts} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace GofkuCam {

//${Evts::EvtSignals} ........................................................
enum EvtSignals : QP::QSignal
{
    FRAME_TIMER_TIMEOUT_SIG  = QP::Q_USER_SIG,
    POLLING_TIMER_TIMEOUT_SIG,
    DEPTH_ESTIMATION_COMPLETED_SIG,
    FRAME_CAPTURED_SIG,
    STREAM_ENDED_SIG,
    CAPTURE_ERROR_SIG,
    START_REQ_SIG,
    STOP_REQ_SIG,
    DEPTH_ESTIMATION_FAILED_SIG,

    MAX_GOFKU_CAM_SIG
};

//${Evts::FrameCapturedEvt} ..................................................
class FrameCapturedEvt : public QP::QEvt {
public:
    std::shared_ptr<Frame> m_frame;

public:
    FrameCapturedEvt()
    : QEvt(EvtSignals::FRAME_CAPTURED_SIG)
    , m_frame{nullptr}
    {}
}; // class FrameCapturedEvt

//${Evts::FrameTimerTimeout} .................................................
class FrameTimerTimeout : public QP::QEvt {
public:
    FrameTimerTimeout()
    : QEvt(EvtSignals::FRAME_TIMER_TIMEOUT_SIG)
    {}
}; // class FrameTimerTimeout

//${Evts::StreamEnded} .......................................................
class StreamEnded : public QP::QEvt {
public:
    StreamEnded();
}; // class StreamEnded

//${Evts::CaptureError} ......................................................
class CaptureError : public QP::QEvt {
public:
    CaptureError();
}; // class CaptureError

//${Evts::StopRequested} .....................................................
class StopRequested : public QP::QEvt {
public:
    StopRequested();
}; // class StopRequested

//${Evts::StartRequested} ....................................................
class StartRequested : public QP::QEvt {
public:
    StartRequested();
}; // class StartRequested

//${Evts::PollingTimerTimeout} ...............................................
class PollingTimerTimeout : public QP::QEvt {
public:
    PollingTimerTimeout();
}; // class PollingTimerTimeout

//${Evts::DepthEstimationCompleted} ..........................................
class DepthEstimationCompleted : public QP::QEvt {
public:
    std::int8_t m_id;

public:
    DepthEstimationCompleted(std::int8_t id);
}; // class DepthEstimationCompleted

//${Evts::DepthEstimationFailed} .............................................
class DepthEstimationFailed : public QP::QEvt {
public:
    DepthEstimationFailed();
}; // class DepthEstimationFailed

} // namespace GofkuCam
//$enddecl${Evts} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
