//$file${../../include/qm~::MqttClient.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${../../include/qm~::MqttClient.hpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../../include/qm~::MqttClient.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef MQTT_CLIENT_HPP_
#define MQTT_CLIENT_HPP_

#include "qpcpp.hpp"
#include "IMqttClient.hpp"
#include "LoggerInterface.hpp"
#include "GofkuCamCommon.hpp"

namespace GofkuCam
{

//$declare${Components::MqttClient} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::MqttClient} ..................................................
class MqttClient : public QP::QActive {
public:
    std::shared_ptr<IMqttClient> m_imqtt_client;

private:
    LoggerInterfacePtr m_logger;

public:
    MqttClient(
        std::string broker_url,
        std::uint32_t broker_port,
        LoggerInterfacePtr logger);

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(NOT_STARTED);
    Q_STATE_DECL(CONNECTED);
    Q_STATE_DECL(DISCONNECTED);
}; // class MqttClient
//$enddecl${Components::MqttClient} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam

#endif
