//.$file${../../include/qm~::Signals.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${../../include/qm~::Signals.hpp}
//
// This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${../../include/qm~::Signals.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef GOFKUCAMSIGNALS_HPP_
#define GOFKUCAMSIGNALS_HPP_

#include "qpcpp.hpp"
#include <opencv2/opencv.hpp>

namespace GofkuCam
{
using Frame = cv::Mat;
using FramePtr = std::shared_ptr<Frame>;
using ActiveObjPtr = QP::QActive*;

enum GofkuCamSignals
{
    IMMEDIATE_TRANSITION_SIG = QP::Q_USER_SIG,

    TIMER_TIMEDOUT_SIG,
    FRAME_CAPTURED_SIG,
    FRAME_GRABBING_FAILED_SIG,

    MAX_GOFKU_CAM_SIG
};

}

#endif