//$file${.::CameraGrabber.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${.::CameraGrabber.cpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::CameraGrabber.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "CameraGrabber.hpp"
#include "Evts.hpp"
#include "Config.hpp"

Q_DEFINE_THIS_FILE

namespace GofkuCam
{

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Components::CameraGrabber} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::CameraGrabber} ...............................................

//${Components::CameraGrabber::CameraGrabber} ................................
CameraGrabber::CameraGrabber(LoggerInterfacePtr logger)
: QActive(&initial)
, m_logger(logger)
, m_frame_timer(this, EvtSignals::FRAME_TIMER_TIMEOUT_SIG, 0U)
{
    m_logger->trace("The Controller ctor!");
}

//${Components::CameraGrabber::SM} ...........................................
Q_STATE_DEF(CameraGrabber, initial) {
    //${Components::CameraGrabber::SM::initial}
    (void)e; // Just to supress compiler warning
    (void)Q_this_module_; // Just to supress compiler warning
    return tran(&NOT_STARTED);
}

//${Components::CameraGrabber::SM::NOT_STARTED} ..............................
Q_STATE_DEF(CameraGrabber, NOT_STARTED) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CameraGrabber::SM::NOT_STARTED::START_REQ}
        case START_REQ_SIG: {
            status_ = tran(&RUNNING);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${Components::CameraGrabber::SM::RUNNING} ..................................
Q_STATE_DEF(CameraGrabber, RUNNING) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CameraGrabber::SM::RUNNING::STREAM_ENDED}
        case STREAM_ENDED_SIG: {
            status_ = tran(&NOT_STARTED);
            break;
        }
        //${Components::CameraGrabber::SM::RUNNING::CAPTURE_ERROR}
        case CAPTURE_ERROR_SIG: {
            status_ = tran(&NOT_STARTED);
            break;
        }
        //${Components::CameraGrabber::SM::RUNNING::FRAME_TIMER_TIMEOUT}
        case FRAME_TIMER_TIMEOUT_SIG: {
            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::CameraGrabber::SM::RUNNING::STOP_REQ}
        case STOP_REQ_SIG: {
            status_ = tran(&NOT_STARTED);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::CameraGrabber} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam
