//$file${.::CameraGrabber.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${.::CameraGrabber.cpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::CameraGrabber.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "CameraGrabber.hpp"
#include "Evts.hpp"
#include "Config.hpp"
#include "CameraGrabberImpl.hpp"
#include "DepthEstimatorController.hpp"

Q_DEFINE_THIS_FILE

namespace GofkuCam
{

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Components::CameraGrabber} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::CameraGrabber} ...............................................

//${Components::CameraGrabber::CameraGrabber} ................................
CameraGrabber::CameraGrabber(
    LoggerInterfacePtr logger,
    std::string source,
    std::vector<std::shared_ptr<DepthEstimatorController>>  depth_estimator_controllers)
: QActive(&initial)
, m_logger(logger)
, m_icamera_grabber{std::make_shared<CameraGrabberImpl>(this, m_logger, depth_estimator_controllers)}
{
    m_logger->trace("The Controller ctor!");
}

//${Components::CameraGrabber::SM} ...........................................
Q_STATE_DEF(CameraGrabber, initial) {
    //${Components::CameraGrabber::SM::initial}
    (void)e; // Just to supress compiler warning
    (void)Q_this_module_; // Just to supress compiler warning


    this->subscribe(START_REQ_SIG);
    this->subscribe(STOP_REQ_SIG);
    this->subscribe(FRAME_TIMER_TIMEOUT_SIG);
    this->subscribe(STREAM_ENDED_SIG);
    this->subscribe(DEPTH_ESTIMATION_COMPLETED_SIG);
    return tran(&NOT_STARTED);
}

//${Components::CameraGrabber::SM::NOT_STARTED} ..............................
Q_STATE_DEF(CameraGrabber, NOT_STARTED) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CameraGrabber::SM::NOT_STARTED::START_REQ}
        case START_REQ_SIG: {
            m_icamera_grabber->start_req(e);

            //${Components::CameraGrabber::SM::NOT_STARTED::START_REQ::[m_icamera_grabber->is_opened()]}
            if (m_icamera_grabber->is_opened()) {
                status_ = tran(&RUNNING);
            }
            else {
                status_ = Q_RET_UNHANDLED;
            }
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${Components::CameraGrabber::SM::RUNNING} ..................................
Q_STATE_DEF(CameraGrabber, RUNNING) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CameraGrabber::SM::RUNNING}
        case Q_ENTRY_SIG: {
            m_icamera_grabber->running_entry(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::CameraGrabber::SM::RUNNING::STREAM_ENDED, CAPTURE_ERROR}
        case STREAM_ENDED_SIG: // intentionally fall through
        case CAPTURE_ERROR_SIG: {
            m_icamera_grabber->stream_end(e);

            status_ = tran(&NOT_STARTED);
            break;
        }
        //${Components::CameraGrabber::SM::RUNNING::FRAME_TIMER_TIMEOUT}
        case FRAME_TIMER_TIMEOUT_SIG: {
            m_icamera_grabber->frame_timer_timeout(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::CameraGrabber::SM::RUNNING::STOP_REQ}
        case STOP_REQ_SIG: {
            m_icamera_grabber->stop_req(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::CameraGrabber::SM::RUNNING::POLLING_TIMER_TIMEOUT}
        case POLLING_TIMER_TIMEOUT_SIG: {
            m_icamera_grabber->poll_the_camera(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::CameraGrabber::SM::RUNNING::DEPTH_ESTIMATION_COMPLETED}
        case DEPTH_ESTIMATION_COMPLETED_SIG: {
            m_icamera_grabber->depth_estimation_completed(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::CameraGrabber} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam
