//$file${.::CatDetector.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${.::CatDetector.cpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::CatDetector.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "ICatDetector.hpp"
#include "CatDetector.hpp"
#include "CatDetectorImpl.hpp"
#include "Evts.hpp"
#include "Config.hpp"

Q_DEFINE_THIS_FILE

namespace GofkuCam
{

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Components::CatDetector} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::CatDetector} .................................................

//${Components::CatDetector::CatDetector} ....................................
CatDetector::CatDetector(LoggerInterfacePtr logger)
: QActive(&initial)
, m_logger(logger)
, m_cat_detector{std::make_shared<CatDetectorImpl>(this, logger)}
{
    m_logger->trace("Cat detector started!");
}

//${Components::CatDetector::SM} .............................................
Q_STATE_DEF(CatDetector, initial) {
    //${Components::CatDetector::SM::initial}
    (void)e; // Just to supress compiler warning
    (void)Q_this_module_; // Just to supress compiler warning

    this->subscribe(START_REQ_SIG);
    this->subscribe(STOP_REQ_SIG);


    return tran(&NOT_STARTED);
}

//${Components::CatDetector::SM::OPERAING} ...................................
Q_STATE_DEF(CatDetector, OPERAING) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CatDetector::SM::OPERAING::FRAME_CAPTURED}
        case FRAME_CAPTURED_SIG: {
            m_cat_detector->frame_captured(e);
            status_ = tran(&WAITING_DETECTORS);
            break;
        }
        //${Components::CatDetector::SM::OPERAING::STREAM_ENDED, CAPTURE_ERROR, STO~}
        case STREAM_ENDED_SIG: // intentionally fall through
        case CAPTURE_ERROR_SIG: // intentionally fall through
        case STOP_REQ_SIG: {
            m_cat_detector->stream_end(e);
            status_ = tran(&NOT_STARTED);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${Components::CatDetector::SM::OPERAING::WAITING_DETECTORS} ................
Q_STATE_DEF(CatDetector, WAITING_DETECTORS) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::OBJECT_DETECTION_COMPLETED}
        case OBJECT_DETECTION_COMPLETED_SIG: {
            m_cat_detector->object_detection_completed(e);
            status_ = tran(&WAITING_DEPTH_MAP);
            break;
        }
        //${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::DEPTH_ESTIMATION_COMPLETED}
        case DEPTH_ESTIMATION_COMPLETED_SIG: {
            m_cat_detector->depth_estimation_completed(e);
            status_ = tran(&WAITING_OBJECT_DETECTION);
            break;
        }
        default: {
            status_ = super(&OPERAING);
            break;
        }
    }
    return status_;
}

//${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::WAITING_OBJECT_DETECTION}
Q_STATE_DEF(CatDetector, WAITING_OBJECT_DETECTION) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::WAITING_OBJECT_D~::OBJECT_DETECTION_COMPLETED}
        case OBJECT_DETECTION_COMPLETED_SIG: {
            status_ = tran(&DETERMINE_CAT_FEEDING);
            break;
        }
        //${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::WAITING_OBJECT_D~::FRAME_CAPTURED}
        case FRAME_CAPTURED_SIG: {
            status_ = tran(&WAITING_DETECTORS);
            break;
        }
        default: {
            status_ = super(&WAITING_DETECTORS);
            break;
        }
    }
    return status_;
}

//${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::WAITING_DEPTH_MAP}
Q_STATE_DEF(CatDetector, WAITING_DEPTH_MAP) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::WAITING_DEPTH_MA~::DEPTH_ESTIMATION_COMPLETED}
        case DEPTH_ESTIMATION_COMPLETED_SIG: {
            status_ = tran(&DETERMINE_CAT_FEEDING);
            break;
        }
        //${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::WAITING_DEPTH_MA~::FRAME_CAPTURED}
        case FRAME_CAPTURED_SIG: {
            status_ = tran(&WAITING_DETECTORS);
            break;
        }
        default: {
            status_ = super(&WAITING_DETECTORS);
            break;
        }
    }
    return status_;
}

//${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::DETERMINE_CAT_FEEDING}
Q_STATE_DEF(CatDetector, DETERMINE_CAT_FEEDING) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CatDetector::SM::OPERAING::WAITING_DETECTOR~::DETERMINE_CAT_FE~::CAT_FEEDING_DETERMINED}
        case CAT_FEEDING_DETERMINED_SIG: {
            status_ = tran(&OPERAING);
            break;
        }
        default: {
            status_ = super(&WAITING_DETECTORS);
            break;
        }
    }
    return status_;
}

//${Components::CatDetector::SM::NOT_STARTED} ................................
Q_STATE_DEF(CatDetector, NOT_STARTED) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::CatDetector::SM::NOT_STARTED::START_REQ}
        case START_REQ_SIG: {
            m_cat_detector->start_req(e);
            status_ = tran(&OPERAING);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::CatDetector} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam
