//.$file${.::Controller.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${.::Controller.cpp}
//
// This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${.::Controller.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "Controller.hpp"
#include "Signals.hpp"
#include "Config.hpp"

Q_DEFINE_THIS_FILE

namespace GofkuCam
{

//.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//. Check for the minimum required QP version
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.9.0 or higher required
#endif
//.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${Components::Controller} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//.${Components::Controller} .................................................
//.${Components::Controller::Controller} .....................................
Controller::Controller(LoggerInterfacePtr logger, FrameGrabbingStrategyPtr frame_grabber, YOLO12DetectorPtr detector)
  : QActive(&initial),
    m_logger(logger),
    m_timer(this, TIMER_TIMEDOUT_SIG, 0U),
    m_detector(detector),
    m_frame_strategy(frame_grabber)
{
    m_logger->trace("The Controller ctor!");
}

//.${Components::Controller::SM} .............................................
Q_STATE_DEF(Controller, initial) {
    //.${Components::Controller::SM::initial}
    (void)e; // Just to supress compiler warning
    (void)Q_this_module_; // Just to supress compiler warning

    m_frame_strategy->subscribeToFrameUpdates(this);
    m_frame_strategy->open();

    return tran(&operating);
}
//.${Components::Controller::SM::operating} ..................................
Q_STATE_DEF(Controller, operating) {
    QP::QState status_;
    switch (e->sig) {
        //.${Components::Controller::SM::operating::FRAME_CAPTURED}
        case FRAME_CAPTURED_SIG: {

            m_frame_strategy->unsubscribeFromFrameUpdates(this);
            Frame frame;
            m_frame_strategy->grabFrame(frame);
            // Detect objects in the frame
            std::vector<Detection> results = m_detector->detect(frame);
            m_frame_strategy->subscribeToFrameUpdates(this);

            std::stringstream ss;
            ss<<"Frame arrived: " << frame.size;
            m_logger->info(ss.str());
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//.$enddef${Components::Controller} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam