//$file${.::Controller.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${.::Controller.cpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Controller.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "Controller.hpp"
#include "Evts.hpp"
#include "Config.hpp"

Q_DEFINE_THIS_FILE

namespace GofkuCam
{

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Components::Controller} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::Controller} ..................................................

//${Components::Controller::Controller} ......................................
Controller::Controller(
    LoggerInterfacePtr logger,
    FrameGrabbingStrategyPtr frame_grabber)
: QActive(&initial)
, m_logger(logger)
, m_timer(this, EvtSignals::TIMER_TIMEDOUT_SIG, 0U)
, m_frame_strategy(frame_grabber)
{
    m_logger->trace("The Controller ctor!");
}

//${Components::Controller::SM} ..............................................
Q_STATE_DEF(Controller, initial) {
    //${Components::Controller::SM::initial}
    (void)e; // Just to supress compiler warning
    (void)Q_this_module_; // Just to supress compiler warning

    m_frame_strategy->subscribeToFrameUpdates(this);
    m_frame_strategy->open();

    return tran(&operating);
}

//${Components::Controller::SM::operating} ...................................
Q_STATE_DEF(Controller, operating) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::Controller::SM::operating::FRAME_CAPTURED}
        case FRAME_CAPTURED_SIG: {
            Frame frame;
            m_frame_strategy->grabFrame(frame);
            std::stringstream ss;
            ss<<"Frame arrived: " << frame.size;
            m_logger->info(ss.str());
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::Controller} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam
