//$file${.::Controller.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${.::Controller.cpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Controller.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "Controller.hpp"
#include "Evts.hpp"
#include "Config.hpp"

Q_DEFINE_THIS_FILE

namespace GofkuCam
{

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Components::Controller} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::Controller} ..................................................

//${Components::Controller::Controller} ......................................
Controller::Controller(
    LoggerInterfacePtr logger,
    std::shared_ptr<ObjectDetector> detector)
: QActive(&initial)
, m_logger(logger)
{
    m_logger->trace("Camera grabber started!");
}

//${Components::Controller::SM} ..............................................
Q_STATE_DEF(Controller, initial) {
    //${Components::Controller::SM::initial}
    (void)e; // Just to supress compiler warning
    (void)Q_this_module_; // Just to supress compiler warning

    return tran(&operating);
}

//${Components::Controller::SM::operating} ...................................
Q_STATE_DEF(Controller, operating) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::Controller::SM::operating::FRAME_CAPTURED}
        case FRAME_CAPTURED_SIG: {
            /*
            m_frame_strategy->unsubscribeFromFrameUpdates(this);
            Frame frame;
            m_frame_strategy->grabFrame(frame);
            // Detect objects in the frame
            #ifdef MINI_PROFILER
            // Mini profiler
            //static int call_count = 0;
            std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();
            #endif

            std::vector<Detection> results = m_detector->detect(frame);
            //m_detector->draw_bounding_box_mask(frame, results);

            #ifdef MINI_PROFILER
            std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
            m_logger->info("Detection took " + std::to_string(std::chrono::duration_cast<std::chrono::milliseconds>(end - begin).count()) + "[ms]");
            #endif
            m_frame_strategy->subscribeToFrameUpdates(this);

            std::stringstream ss;
            ss<<"Frame processed: " << frame.size;
            m_logger->info(ss.str());
            */
            m_logger->info("New frame");
            std::shared_ptr<Frame> frame = Q_EVT_CAST(FrameCapturedEvt)->m_frame;
            m_logger->trace("Captured frame with size: " + std::to_string(frame->cols) + "x" + std::to_string(frame->rows));

            // Display the frame
            cv::imshow("GofkuCam Stream", *frame);
            cv::waitKey(500); // Allow the window to update, wait 1ms
            cv::destroyAllWindows();
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::Controller} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam
