//$file${.::DetectorController.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${.::DetectorController.cpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::DetectorController.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "IDetectorController.hpp"
#include "DetectorController.hpp"
#include "DetectorControllerImpl.hpp"
#include "Evts.hpp"
#include "Config.hpp"

Q_DEFINE_THIS_FILE

namespace GofkuCam
{

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Components::DetectorController} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::DetectorController} ..........................................

//${Components::DetectorControll~::DetectorController} .......................
DetectorController::DetectorController(LoggerInterfacePtr logger)
: QActive(&initial)
, m_logger(logger)
, m_detector_controller{std::make_shared<DetectorControllerImpl>(this, logger)}
{
    m_logger->trace("Object Detector started!");
}

//${Components::DetectorControll~::SM} .......................................
Q_STATE_DEF(DetectorController, initial) {
    //${Components::DetectorControll~::SM::initial}
    (void)e; // Just to supress compiler warning
    (void)Q_this_module_; // Just to supress compiler warning

    this->subscribe(START_REQ_SIG);
    this->subscribe(STOP_REQ_SIG);
    return tran(&NOT_STARTED);
}

//${Components::DetectorControll~::SM::operating} ............................
Q_STATE_DEF(DetectorController, operating) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::DetectorControll~::SM::operating::FRAME_CAPTURED}
        case FRAME_CAPTURED_SIG: {
            m_detector_controller->frame_captured(e);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::DetectorControll~::SM::operating::STREAM_ENDED, CAPTURE_ERROR, STO~}
        case STREAM_ENDED_SIG: // intentionally fall through
        case CAPTURE_ERROR_SIG: // intentionally fall through
        case STOP_REQ_SIG: {
            m_detector_controller->stream_end(e);
            status_ = tran(&NOT_STARTED);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${Components::DetectorControll~::SM::NOT_STARTED} ..........................
Q_STATE_DEF(DetectorController, NOT_STARTED) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::DetectorControll~::SM::NOT_STARTED::START_REQ}
        case START_REQ_SIG: {
            m_detector_controller->start_req(e);
            status_ = tran(&operating);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::DetectorController} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam
