//$file${.::MqttClient.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: gofkucam.qm
// File:  ${.::MqttClient.cpp}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::MqttClient.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "MqttClient.hpp"
#include "Evts.hpp"
#include "Config.hpp"
#include "MqttClientImpl.hpp"

Q_DEFINE_THIS_FILE

namespace GofkuCam
{

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Components::MqttClient} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::MqttClient} ..................................................

//${Components::MqttClient::MqttClient} ......................................
MqttClient::MqttClient(
    std::string broker_url,
    std::uint32_t broker_port,
    LoggerInterfacePtr logger)
: QActive(&initial)
, m_imqtt_client{std::make_shared<MqttClientImpl>(this, broker_url, broker_port, logger)}
, m_logger(logger)
{
    m_logger->info("The MqttClient ctor!");
}

//${Components::MqttClient::SM} ..............................................
Q_STATE_DEF(MqttClient, initial) {
    //${Components::MqttClient::SM::initial}
    (void)e; // Just to supress compiler warning
    (void)Q_this_module_; // Just to supress compiler warning


    this->subscribe(START_REQ_SIG);
    this->subscribe(STOP_REQ_SIG);
    return tran(&NOT_STARTED);
}

//${Components::MqttClient::SM::NOT_STARTED} .................................
Q_STATE_DEF(MqttClient, NOT_STARTED) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::MqttClient::SM::NOT_STARTED}
        case Q_ENTRY_SIG: {
            m_imqtt_client->not_started_entry(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::MqttClient::SM::NOT_STARTED}
        case Q_EXIT_SIG: {
            m_imqtt_client->not_started_exit(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::MqttClient::SM::NOT_STARTED::START_REQ}
        case START_REQ_SIG: {
            m_imqtt_client->start_req(e);

            //${Components::MqttClient::SM::NOT_STARTED::START_REQ::[m_imqtt_client->is_connected()]}
            if (m_imqtt_client->is_connected()) {
                status_ = tran(&CONNECTED);
            }
            else {
                status_ = Q_RET_UNHANDLED;
            }
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${Components::MqttClient::SM::CONNECTED} ...................................
Q_STATE_DEF(MqttClient, CONNECTED) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::MqttClient::SM::CONNECTED}
        case Q_ENTRY_SIG: {
            m_imqtt_client->connected_entry(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::MqttClient::SM::CONNECTED}
        case Q_EXIT_SIG: {
            m_imqtt_client->connected_exit(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::MqttClient::SM::CONNECTED::CAT_FEEDING_DETERMINED}
        case CAT_FEEDING_DETERMINED_SIG: {
            m_imqtt_client->cat_feeding_result(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::MqttClient::SM::CONNECTED::STOP_REQ}
        case STOP_REQ_SIG: {
            m_imqtt_client->stop_req(e);

            status_ = tran(&NOT_STARTED);
            break;
        }
        //${Components::MqttClient::SM::CONNECTED::DISCONNECTED_FROM_BROKER}
        case DISCONNECTED_FROM_BROKER_SIG: {
            status_ = tran(&DISCONNECTED);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${Components::MqttClient::SM::DISCONNECTED} ................................
Q_STATE_DEF(MqttClient, DISCONNECTED) {
    QP::QState status_;
    switch (e->sig) {
        //${Components::MqttClient::SM::DISCONNECTED}
        case Q_ENTRY_SIG: {
            m_imqtt_client->disconnected_entry(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::MqttClient::SM::DISCONNECTED}
        case Q_EXIT_SIG: {
            m_imqtt_client->disconnected_exit(e);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${Components::MqttClient::SM::DISCONNECTED::RECONNECTION_TIMER_TIMED_OUT}
        case RECONNECTION_TIMER_TIMED_OUT_SIG: {
            m_imqtt_client->reconnection_timer_timed_out(e);

            //${Components::MqttClient::SM::DISCONNECTED::RECONNECTION_TIM~::[m_imqtt_client->is_connected()]}
            if (m_imqtt_client->is_connected()) {
                status_ = tran(&CONNECTED);
            }
            else {
                status_ = Q_RET_UNHANDLED;
            }
            break;
        }
        //${Components::MqttClient::SM::DISCONNECTED::STOP_REQ}
        case STOP_REQ_SIG: {
            m_imqtt_client->stop_req(e);

            status_ = tran(&NOT_STARTED);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${Components::MqttClient} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

} // namespace GofkuCam
